//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Canal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bridge {
            get {
                object obj = ResourceManager.GetObject("bridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.3
        ///- Tidied up tab area: former Performs view is now integrated into Table of Contents and searchable
        ///- Improved info area: Programs, procedures and variables have their own view with context sensitive information
        ///
        ///v2.2.3
        ///- Fixed bug where WordInfo (if you double click on a variable) would not show the root variable
        ///
        ///v2.2.2
        ///- Recent files and file-type-selection work again
        ///- Missing REDEFINES-references doesn&apos;t crash analysis anymore
        ///- Fixed issue #11 (SetFoldingMarker)
        ///- Added support for BINA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        internal static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: CobolTree could not be built: .
        /// </summary>
        internal static string Error_CobolTree_could_not_be_built {
            get {
                return ResourceManager.GetString("Error_CobolTree_could_not_be_built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured trying to display the file: .
        /// </summary>
        internal static string ErrorMessage_FileControl_Constructor {
            get {
                return ResourceManager.GetString("ErrorMessage_FileControl_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file: .
        /// </summary>
        internal static string ErrorMessage_MainWindow_ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorMessage_MainWindow_ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to restore previously opened files: .
        /// </summary>
        internal static string ErrorMessage_MainWindow_OpenPrevious {
            get {
                return ResourceManager.GetString("ErrorMessage_MainWindow_OpenPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorWithMessage {
            get {
                return ResourceManager.GetString("ErrorWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found..
        /// </summary>
        internal static string File_Could_Not_Be_Found {
            get {
                return ResourceManager.GetString("File_Could_Not_Be_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be found..
        /// </summary>
        internal static string FileCouldNotBeFound {
            get {
                return ResourceManager.GetString("FileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Copybooks.
        /// </summary>
        internal static string FilterCopybooksWindowTitle {
            get {
                return ResourceManager.GetString("FilterCopybooksWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Matching Files Found.
        /// </summary>
        internal static string MultipleFilesFound {
            get {
                return ResourceManager.GetString("MultipleFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple files matching this program name. Try files tab to open program..
        /// </summary>
        internal static string MultipleFilesMatchSearch {
            get {
                return ResourceManager.GetString("MultipleFilesMatchSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Would you like to close this tab anyway?.
        /// </summary>
        internal static string ReallyCloseThisTab {
            get {
                return ResourceManager.GetString("ReallyCloseThisTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Procedure: .
        /// </summary>
        internal static string SelectedProcedure {
            get {
                return ResourceManager.GetString("SelectedProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: .
        /// </summary>
        internal static string SelectedProgram {
            get {
                return ResourceManager.GetString("SelectedProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Variable: .
        /// </summary>
        internal static string SelectedVariable {
            get {
                return ResourceManager.GetString("SelectedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_Bold {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_BoldIt {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_BoldIt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_It {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_It", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_Regular {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
