//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Canal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bridge {
            get {
                object obj = ResourceManager.GetObject("bridge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.13
        ///- new search option: fuzzy search
        ///- generated enums now have a value
        ///- bugfix: ctrl+c restored
        ///
        ///v2.12
        ///- COPY-books can be found without explicit folder name (&quot;OF&quot;) if filename is unique (@koljag)
        ///- Double-clicking a variable now selects it in the variable tree (@koljag)
        ///- Tree-view now highlights the currently displayed procedure (@koljag)
        ///- .cob and .cbl files are now treated separately (@koljag)
        ///
        ///v2.11
        ///- &quot;Referenced By&quot; now jumps to the line where the &quot;perform&quot; is
        ///- Added support for mu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current project without saving?.
        /// </summary>
        internal static string Close_current_project_without_saving {
            get {
                return ResourceManager.GetString("Close_current_project_without_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        internal static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has changed. Re-run analysis now?.
        /// </summary>
        internal static string CodeHasChanged_Text {
            get {
                return ResourceManager.GetString("CodeHasChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has changed.
        /// </summary>
        internal static string CodeHasChanged_Title {
            get {
                return ResourceManager.GetString("CodeHasChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CollapseAllButton_Image {
            get {
                object obj = ResourceManager.GetObject("CollapseAllButton_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: CobolTree could not be built: .
        /// </summary>
        internal static string Error_CobolTree_could_not_be_built {
            get {
                return ResourceManager.GetString("Error_CobolTree_could_not_be_built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured trying to display the file: .
        /// </summary>
        internal static string ErrorMessage_FileControl_Constructor {
            get {
                return ResourceManager.GetString("ErrorMessage_FileControl_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file: .
        /// </summary>
        internal static string ErrorMessage_MainWindow_ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorMessage_MainWindow_ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to restore previously opened files: .
        /// </summary>
        internal static string ErrorMessage_MainWindow_OpenPrevious {
            get {
                return ResourceManager.GetString("ErrorMessage_MainWindow_OpenPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorWithMessage {
            get {
                return ResourceManager.GetString("ErrorWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExpandAllButton_Image {
            get {
                object obj = ResourceManager.GetObject("ExpandAllButton_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found..
        /// </summary>
        internal static string File_Could_Not_Be_Found {
            get {
                return ResourceManager.GetString("File_Could_Not_Be_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file: .
        /// </summary>
        internal static string FileControl_Save_Error_saving_file {
            get {
                return ResourceManager.GetString("FileControl_Save_Error_saving_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be found..
        /// </summary>
        internal static string FileCouldNotBeFound {
            get {
                return ResourceManager.GetString("FileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Copybooks.
        /// </summary>
        internal static string FilterCopybooksWindowTitle {
            get {
                return ResourceManager.GetString("FilterCopybooksWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANAL Cobol Analyzer.
        /// </summary>
        internal static string Main_Name_Long {
            get {
                return ResourceManager.GetString("Main_Name_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANAL.
        /// </summary>
        internal static string Main_Name_Short {
            get {
                return ResourceManager.GetString("Main_Name_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Matching Files Found.
        /// </summary>
        internal static string MultipleFilesFound {
            get {
                return ResourceManager.GetString("MultipleFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple files matching this program name. Try files tab to open program..
        /// </summary>
        internal static string MultipleFilesMatchSearch {
            get {
                return ResourceManager.GetString("MultipleFilesMatchSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported..
        /// </summary>
        internal static string Not_supported {
            get {
                return ResourceManager.GetString("Not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains an Identification, Environment and Data Division, but no Procedure Division. This might be hidden in a copy book. You can insert code from copy books and re-run analysis. Open copy book selection now?.
        /// </summary>
        internal static string ProcedureDivisionMissing_Text {
            get {
                return ResourceManager.GetString("ProcedureDivisionMissing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Division missing.
        /// </summary>
        internal static string ProcedureDivisionMissing_Title {
            get {
                return ResourceManager.GetString("ProcedureDivisionMissing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines incl. performs not calculated due to recursion..
        /// </summary>
        internal static string ProcedureInfo_LinesOfCodeError {
            get {
                return ResourceManager.GetString("ProcedureInfo_LinesOfCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project files are not supported in this version of Canal..
        /// </summary>
        internal static string Project_files_are_not_supported_in_this_version_of_Canal {
            get {
                return ResourceManager.GetString("Project_files_are_not_supported_in_this_version_of_Canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid filepath..
        /// </summary>
        internal static string ProjectAssistant_StartAnalysisButton_Click_Please_enter_a_valid_filepath_ {
            get {
                return ResourceManager.GetString("ProjectAssistant_StartAnalysisButton_Click_Please_enter_a_valid_filepath_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid project name..
        /// </summary>
        internal static string ProjectAssistant_StartAnalysisButton_Click_Please_enter_a_valid_project_name_ {
            get {
                return ResourceManager.GetString("ProjectAssistant_StartAnalysisButton_Click_Please_enter_a_valid_project_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one file type..
        /// </summary>
        internal static string ProjectAssistant_StartAnalysisButton_Click_Please_select_at_least_one_file_type_ {
            get {
                return ResourceManager.GetString("ProjectAssistant_StartAnalysisButton_Click_Please_select_at_least_one_file_type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project creation failed: .
        /// </summary>
        internal static string ProjectAssistant_StartAnalysisButton_Click_Project_creation_failed__ {
            get {
                return ResourceManager.GetString("ProjectAssistant_StartAnalysisButton_Click_Project_creation_failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening project: .
        /// </summary>
        internal static string ProjectUtil_Open_Error_opening_project__ {
            get {
                return ResourceManager.GetString("ProjectUtil_Open_Error_opening_project__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving project: .
        /// </summary>
        internal static string ProjectUtil_Save_Error_saving_project__ {
            get {
                return ResourceManager.GetString("ProjectUtil_Save_Error_saving_project__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Would you like to close this tab anyway?.
        /// </summary>
        internal static string ReallyCloseThisTab {
            get {
                return ResourceManager.GetString("ReallyCloseThisTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really revert all changes to last saved version?.
        /// </summary>
        internal static string RevertChanges_Text {
            get {
                return ResourceManager.GetString("RevertChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Changes....
        /// </summary>
        internal static string RevertChanges_Title {
            get {
                return ResourceManager.GetString("RevertChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for &quot;FILLER&quot; is not supported..
        /// </summary>
        internal static string SearchingForFillerNotSupported {
            get {
                return ResourceManager.GetString("SearchingForFillerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Procedure: .
        /// </summary>
        internal static string SelectedProcedure {
            get {
                return ResourceManager.GetString("SelectedProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program: .
        /// </summary>
        internal static string SelectedProgram {
            get {
                return ResourceManager.GetString("SelectedProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Variable: .
        /// </summary>
        internal static string SelectedVariable {
            get {
                return ResourceManager.GetString("SelectedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_Bold {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_BoldIt {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_BoldIt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_It {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_It", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SourceCodePro_Regular {
            get {
                object obj = ResourceManager.GetObject("SourceCodePro_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
